#!/bin/busybox sh
# shellcheck shell=sh
# shellcheck disable=SC2039
#
# Really, this should be ash, not sh, but shellcheck doesn't support ash, see
# https://github.com/koalaman/shellcheck/issues/853
# SC2039 is there because of that (local/== unsupported in sh, work in ash)

# This is the init script built into the PrawnOS initramfs

# This file is part of PrawnOS (https://www.prawnos.com)
# Copyright (c) 2018 Hal Emmerich <hal@halemmerich.com>

# PrawnOS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.

# PrawnOS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with PrawnOS.  If not, see <https://www.gnu.org/licenses/>.

echo In PrawnOS Init

#used to parse the kernel cmdline
cmdline() {
    local value
    value=" $(cat /proc/cmdline) "
    value="${value##* ${1}=}"
    value="${value%% *}"
    [ "${value}" != "" ] && echo "${value}"
}

# start an ssh server
ssh_server() {
    # setup network
    /usr/sbin/ifconfig eth0 up
    /usr/sbin/ifconfig eth1 up
    udhcpc --retries 5 --quit --script /bin/udhcp_simple.script
    echo "dhcp complete. Configuration:"
    /usr/sbin/ifconfig

    # mount pseudoterminal, start sshd
    mkdir /dev/pts
    mount -t devpts none /dev/pts
    /usr/sbin/sshd
}

rescue_shell() {
   ssh_server
   echo "sshd server started, entering rescueshell..."
   /bin/sh
}


[ -d /dev ] || mkdir -m 0755 /dev
[ -d /sys ] || mkdir /sys
[ -d /proc ] || mkdir /proc
[ -d /tmp ] || mkdir /tmp


mount -n -t proc     proc      /proc
mount -n -t sysfs    sysfs     /sys
mount -n -t devtmpfs devtmpfs  /dev

mkdir -p /newroot
mkdir -p /boot

# TODO waiting for the sd card to be detected by the kernel... sleeping is lame
# why isn't rootwait/root cmdline arg working here?
echo "Waiting for the kernel to see the boot device..."
sleep 2

# get the root device, so we can find the boot partiton
STORAGENODE=$(cmdline root)

#TODO it would be nice if uboot put a root=/dev/mmc* on the cmdline for us
if echo $STORAGENODE | grep -q "DEV=sdcard"; then
  echo "Booting from sd..."
  ROOT_BLKID=$(/sbin/blkid | grep "sdrootfs" )
  BOOT_BLKID=$(/sbin/blkid | grep "sdboot" )

elif echo $STORAGENODE | grep -q "DEV=emmc"; then
  echo "Booting from emmc..."
  ROOT_BLKID=$(/sbin/blkid | grep "emmcrootfs" )
  BOOT_BLKID=$(/sbin/blkid | grep "emmcboot" )

else
  echo $STORAGENODE is not a valid boot device
  exit 1

fi

echo ROOT_BLKID: $ROOT_BLKID
# strip off everything after the colon
ROOTFS="${ROOT_BLKID%:*}"
echo ROOTFS: $ROOTFS

echo BOOT_BLKID: $BOOT_BLKID
# strip off everything after the colon
BOOTFS="${BOOT_BLKID%:*}"
echo BOOTFS: $BOOTFS

# mount /boot so we can read configuration
mount $BOOTFS /boot || rescue_shell

if blkid $ROOTFS | grep -q crypto_LUKS; then
    # start the ssh server so a user can decrypt and mount the root filesystem
    ssh_server

    echo "CRYPTO_ROOTFS=${ROOTFS}" >> /root/.profile
    echo "sshd server started, waiting for decryption of ${ROOTFS}"
    # disable kernel log messages to avoid clashing with the prompt
    dmesg -n 2
    # start shell to allow for local decryption
    export CRYPTO_ROOTFS=${ROOTFS}
    /bin/sh
else
    # mount the unencrypted root filesystem
    mount $ROOTFS /newroot || rescue_shell
fi

# /dev/pts may not be mounted
umount /dev/pts || true
umount /sys
umount /proc

#switch to the new rootfs
exec switch_root /newroot /sbin/init